name: CI Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3


      - name: Python versiyonu kontrol
        run: python3 --version


      - name: Basit test
        run: echo "Testler gecti!"


     
